In [3]:
# 1.7.1 データを読み込む
from sklearn.datasets import load_iris

iris_dataset=load_iris()
print("keys of iris_dataset:\n{}".format( iris_dataset.keys() ))

keys of iris_dataset:
dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])


In [4]:
print( iris_dataset['DESCR'][:193]+"\n..." )

Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive att
...


In [11]:
print( "data:\n{}".format( iris_dataset['data'] ) )

data:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 

In [13]:
print( "target:\n{}".format( iris_dataset['target'] ) )

target:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [16]:
print( "target names:\n{}".format( iris_dataset['target_names'] ) )

target names:
['setosa' 'versicolor' 'virginica']


In [18]:
print( "feature names:\n{}".format( iris_dataset['feature_names'] ) )

feature names:
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [20]:
print( "type of data:\n{}\n".format( type(iris_dataset['data']) ) )
print( "shape of data:\n{}".format( iris_dataset['data'].shape ) )

type of data:
<class 'numpy.ndarray'>

shape of data:
(150, 4)


In [24]:
# p.18
from sklearn.model_selection import train_test_split
'''
train_test_splitはデータをテスト用と訓練用に分割する前にデータをシャッフルする
'''

x_train,x_test,y_train,y_test=train_test_split( iris_dataset['data'],
                                                iris_dataset['target'],
                                                random_state=0
                                              )
'''
同じ関数を何度か呼び出した際に、確実に同じ結果が得られるように、randon_stateパラメータ
を用いて擬似乱数生成器に同じシードを渡している。
これによって出力が決定的になり、常に同じ結果が得られるようになる。
'''

'\n同じ関数を何度か呼び出した際に、確実に同じ結果が得られるように、randon_stateパラメータ\nを用いて擬似乱数生成器に同じシードを渡している。\nこれによって出力が決定的になり、常に同じ結果が得られるようになる。\n'

In [28]:
print( "x_train shape : {}\n".format(x_train.shape) )
print( "x_test shape : {}\n".format(x_test.shape) )
print( "y_train shape : {}\n".format(y_train.shape) )
print( "y_test shape : {}\n".format(y_test.shape) )

x_train shape : (112, 4)

x_test shape : (38, 4)

y_train shape : (112,)

y_test shape : (38,)



In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import mglearn
from IPython.display import display

iris_dataframe=pd.DataFrame( x_train,columns=iris_dataset.feature_names )
'''
x_trainのデータからdataFrameをつくる
iris_dataset.feature_nameの文字列を使ってカラムに名前をつける
'''
grr=pd.scatter_matrix( iris_dataframe,c=y_train,figsize=(15,15),marker='0',
                     hist_kwds={'bins':20},s=60,alpha=8,cmap=mglearn.cm3
                     )
#scatter_matrix()はペアプロットを作成する関数

NameError: name 'x_train' is not defined

In [1]:
'''
k-最近傍法はｋ個の近傍点を用いることに由来する
'''

from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier( n_neighbors=1 )
# まずはクラス（関数）のインスタンスを生成して、近傍店の数も設定する

knn.fit( x_train,y_train )
# fit()は訓練セットからモデルをを構築する
# またfit()はknnオブジェクトそのものを返す（同時にknnを書き換える）ので、出力にこのクラ
# ス分類オブジェクトの文字列表現が表示されている。この文字列表現から、モデルを構築する
# 際に用いられたパラメータガわかる。ほとんどのパラメータはデフォルトである

NameError: name 'x_train' is not defined

In [43]:
# p22, このモデルを使ってラベルがわかっていない新しいデータに対して予想をしてみる
print( "feature name:\n{}".format(iris_dataset['feature_names']) )
x_new=np.array([[5,2.9,1,0.2]])# という測定結果を持つアイリスの品種をよそうさせる
# scikit-learnは二次元のnumpy配列を原則としているから
print("x_new of shape:\n{}".format(x_new.shape))

# 予測を行うにはknnのpredict()を使う
prediction=knn.predict(x_new)
print( "predict target name :\n{}".format( iris_dataset['target_names'][prediction] ))
print("prediction:\n{}".format(prediction))

feature name:
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
x_new of shape:
(1, 4)
predict target name :
['setosa']
prediction:
[0]


In [56]:
# 1.7.6 モデルの評価
print( "test set :\n{}".format(y_test) )

y_predict=knn.predict(x_test)
print( "test set predictions:\n{}".format(y_predict) )
print("test set score :\n{:.2f}".format(np.mean(y_predict==y_test) )  )
print("test set score :\n{:.2f}".format(knn.score(x_test,y_test) )  )
# mean()もaverage()も平均を求める関数。後者は重み付きの平均を求められる

test set :
[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 1]
test set predictions:
[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]
test set score :
0.97
test set score :
0.97


In [59]:
# p24 
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(  iris_dataset['data'],
                                             iris_dataset['target'],
                                             random_state=0
                                             )

from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=1)# k-nearest neighbors(knn)を設定
knn.fit(X_train,Y_train) #　訓練セットからモデルを構築

print( "test set score :\n{:.2f}".format(knn.score(X_test,Y_test) )  )

test set score :
0.97
